Repository micronaut-projects/micronaut-discovery-client, pull requests merged in 2020-09, with the labels that each got.

#61 bump up docs to 1.0.24
  gradle.properties
Labels: relates-to: build

#62 buidl: set oci-java-sdk to 1.21.0
  discovery-client/build.gradle
Labels: relates-to: build

#64 build: remove docs-examples block
  build.gradle
Labels: relates-to: build

#65 Several logging improvements
  discovery-client/src/main/java/io/micronaut/discovery/consul/registration/ConsulAutoRegistration.java
Labels: type: improvement

#67 Bump oci java sdk
  discovery-client/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#66 ci: set github branch and github core branch
  gradle.properties
Labels: relates-to: build

#72 replace in java matrix 14 with 15
  .github/workflows/gradle.yml
Labels: relates-to: build

#73 set java matrix to 15 instead of 14
  .github/workflows/gradle.yml
Labels: relates-to: build

#74 Update com.oracle.oci.sdk to 1.23.3
  discovery-client/build.gradle
Labels: type: dependency-upgrade
