Repository micronaut-projects/micronaut-discovery-client, pull requests merged in 2020-08, with the labels that each got.

#35 Dependency upgrades
  discovery-client/build.gradle
Labels: type: dependency-upgrade

#38 Dependency upgrades
  discovery-client/build.gradle
Labels: type: dependency-upgrade

#39 Add repository section
  src/main/docs/guide/repository.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#40 Dependency upgrades
  discovery-client/build.gradle
Labels: type: dependency-upgrade

#45 [discovery-client] Update common files for branch 2.0.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#44 [discovery-client] Update common files for branch master
  README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#46 Dependency upgrades
  discovery-client/build.gradle
Labels: type: dependency-upgrade
