Repository micronaut-projects/micronaut-discovery-client, pull requests merged in 2023-02, with the labels that each got.

#407 Mergeup 3.3.x
  discovery-client-bom/build.gradle
  gradle.properties
  settings.gradle
Labels: relates-to: build

#404 build: enable binary compatibility
  discovery-client-bom/build.gradle
Labels: relates-to: build

#409 [discovery-client] Update common files for branch
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#412 [discovery-client] Update common files for branch master
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: relates-to: build

#413 Add native test for consul discovery
  .github/workflows/graalvm.yml
  gradle/libs.versions.toml
  settings.gradle
  test-suite-consul-graal/build.gradle.kts
  test-suite-consul-graal/src/test/java/io/micronaut/consul/graal/ConsulTest.java
  test-suite-consul-graal/src/test/java/io/micronaut/consul/graal/GatewayController.java
  test-suite-consul-graal/src/test/java/io/micronaut/consul/graal/HelloClient.java
  test-suite-consul-graal/src/test/java/io/micronaut/consul/graal/HelloController.java
  test-suite-consul-graal/src/test/resources/application.yml
  test-suite-consul-graal/src/test/resources/logback.xml
Labels: relates-to: build, relates-to: graal

#415 Spring cloud client basic authentication support
  discovery-client/src/main/java/io/micronaut/discovery/spring/config/SpringCloudClientConfiguration.java
  discovery-client/src/main/java/io/micronaut/discovery/spring/config/SpringCloudConfigurationClient.java
  discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/SpringCloudConfigClient.java
  discovery-client/src/test/groovy/io/micronaut/discovery/spring/MockSpringCloudConfigSecuredServer.java
  discovery-client/src/test/groovy/io/micronaut/discovery/spring/MockSpringCloudConfigServer.java
  discovery-client/src/test/groovy/io/micronaut/discovery/spring/SpringCloudConfigSecuredTest.groovy
Labels: type: enhancement

#416 Switch to http status check instead of reading the logs
  test-suite-consul-graal/src/test/resources/application.yml
Labels: relates-to: build

#417 [discovery-client] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build
