Repository micronaut-projects/micronaut-discovery-client, pull requests merged in 2024-04, with the labels that each got.

#602 [discovery-client] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#604 fix(deps): update dependency io.micronaut:micronaut-core-bom to v4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#609 Document required HTTP Client dependency.
  src/main/docs/guide/introduction.adoc
Labels: type: docs
